export const fusionGraphStyles = {
  xAxisName: 'Quarter',
  yAxisName: 'Amount {br}(In USD)',
  xAxisPosition: 'top', // "right" ,"'
  yAxisPosition: 'right',
  xAxisNameFont: 'Arial',
  xAxisNameFontSize: '12',
  xAxisNameFontColor: '#993300',
  xAxisNameFontBold: '1',
  xAxisNameFontItalic: '1',
  xAxisNameBorderColor: '#6666FF',
  xAxisNameBorderAlpha: '50',
  xAxisNameBorderPadding: '6',
  xAxisNameBorderRadius: '3',
  xAxisNameBorderThickness: '2',
  xAxisNameBorderDashed: '1',
  xAxisNameBorderDashLen: '4',
  xAxisNameBorderDashGap: '2',
  xAxisNameBgColor: '#3399ff',
  xAxisNameBgAlpha: '20',
  xAxisNameFontAlpha: '50',
  yAxisValueBgColor: '#ff0000',
  yAxisValueBgAlpha: '40',
  yAxisValueBorderColor: '#ff0000',
  yAxisValueBorderAlpha: '60',
  yAxisValueBorderPadding: '5',
  yAxisValueBorderRadius: '2',
  yAxisValueBorderThickness: '3',
  yAxisValueBorderDashed: '1',
  yAxisValueBorderDashLen: '2',
  yAxisValueBorderDashGap: '2',
  yAxisValueFont: 'verdana,sans',
  yAxisValueFontSize: '10px',
  yAxisValueFontColor: '#ff0000',
  yAxisValueFontBold: '1',
  yAxisValueFontItalic: '1',
  yAxisValueAlpha: '50',
  pYAxisName: 'Amount (In USD)',
  sYAxisName: 'Profit %',
  pYAxisNameFont: 'Arial',
  pYAxisNameFontSize: '12',
  pYAxisNameFontColor: '#003366',
  pYAxisNameFontBold: '1',
  pYAxisNameFontItalic: '1',
  pYAxisNameFontAlpha: '50',
  sYAxisNameFont: 'Arial',
  sYAxisNameFontSize: '12',
  sYAxisNameFontColor: '#003366',
  sYAxisNameFontBold: '1',
  sYAxisNameFontItalic: '1',
  sYAxisNameFontAlpha: '50',
  pYAxisNameBgColor: '#3399ff',
  pYAxisNameBgAlpha: '20',
  pYAxisNameBorderPadding: '6',
  pYAxisNameAlpha: '50',
  sYAxisNameBgColor: '#3399ff',
  sYAxisNameBgAlpha: '20',
  sYAxisNameBorderPadding: '6',
  sYAxisNameAlpha: '50',
  pYAxisNameBorderColor: '#6666FF',
  pYAxisNameBorderAlpha: '50',
  pYAxisNameBorderRadius: '0',
  pYAxisNameBorderThickness: '1',
  pYAxisNameBorderDashed: '1',
  pYAxisNameBorderDashLen: '4',
  pYAxisNameBorderDashGap: '2',
  sYAxisNameBorderColor: '#6666FF',
  sYAxisNameBorderAlpha: '50',
  sYAxisNameBorderRadius: '0',
  sYAxisNameBorderThickness: '1',
  sYAxisNameBorderDashed: '1',
  sYAxisNameBorderDashLen: '4',
  sYAxisNameBorderDashGap: '2',
  scrollPosition: 'top', // 'left',
  decimals: '4',
  yAxisValueDecimals: '2',
  xAxisValueDecimals: '3'
};
