export enum FusionChartEnum {
  column2d = 'column2d',
  scrollcolumn2d = 'scrollcolumn2d',
  column3D = 'column3D',
  bar2D = 'bar2D',
  scrollbar2d = 'scrollbar2d',
  bar3D = 'bar3D',
  msbar2d = 'msbar2d',
  pie2d = 'pie2d',
  overlappedcolumn2d = 'overlappedcolumn2d',
  overlappedbar2d = 'overlappedbar2d',
  stackedcolumn2d = 'stackedcolumn2d',
  msstackedcolumn2d = 'msstackedcolumn2d',
  doughnut2d = 'doughnut2d',
  stackedarea2d = 'stackedarea2d',
  doughnut3d = 'doughnut3d',
  multilevelpie = 'multilevelpie',
  line = 'line',
  msline = 'msline',
  multiaxisline = 'multiaxisline',
  area = 'area',
  stackedbar2d = 'stackedbar2d'
}
